//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPS.TaxDeterminationImporter.Core.DAO {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPS.TaxDeterminationImporter.Core.DAO.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT BPLId FROM OBPL.
        /// </summary>
        internal static string Branch_Get {
            get {
                return ResourceManager.GetString("Branch_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT CardCode FROM OCRD WHERE CardCode = &apos;{0}&apos;.
        /// </summary>
        internal static string BusinessPartner_Get {
            get {
                return ResourceManager.GetString("BusinessPartner_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT GroupCode Id, GroupName Code FROM OCRG WHERE GroupType = &apos;C&apos;.
        /// </summary>
        internal static string CustomerGroup_Get {
            get {
                return ResourceManager.GetString("CustomerGroup_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT ItemCode FROM OITM WHERE ItemCode = &apos;{0}&apos;.
        /// </summary>
        internal static string Item_Get {
            get {
                return ResourceManager.GetString("Item_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT ItmsGrpCod Id, ItmsGrpNam Code FROM OITB.
        /// </summary>
        internal static string ItemGroup_Get {
            get {
                return ResourceManager.GetString("ItemGroup_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT MatGrp FROM OMGP.
        /// </summary>
        internal static string MaterialGroup_Get {
            get {
                return ResourceManager.GetString("MaterialGroup_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT AbsEntry Id, NcmCode Code FROM ONCM WHERE NcmCode = &apos;{0}&apos;.
        /// </summary>
        internal static string Ncm_Get {
            get {
                return ResourceManager.GetString("Ncm_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT AbsEntry Id, NcmCode Code FROM ONCM WHERE NcmCode = &apos;{0}&apos;.
        /// </summary>
        internal static string Ncm_GetByCode {
            get {
                return ResourceManager.GetString("Ncm_GetByCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Code FROM OCST.
        /// </summary>
        internal static string State_Get {
            get {
                return ResourceManager.GetString("State_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT GroupCode Id, GroupName Code FROM OCRG WHERE GroupType = &apos;S&apos;.
        /// </summary>
        internal static string SupplierGroup_Get {
            get {
                return ResourceManager.GetString("SupplierGroup_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT Code FROM OSTC.
        /// </summary>
        internal static string Tax_Get {
            get {
                return ResourceManager.GetString("Tax_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT AbsId FROM TCD1 WHERE Priority = {0}.
        /// </summary>
        internal static string TaxDetermination_GetByPriority {
            get {
                return ResourceManager.GetString("TaxDetermination_GetByPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT DispOrder FROM TCD2
        ///WHERE KeyFld_1_V = &apos;{0}&apos;
        ///AND ISNULL(KeyFld_2_V, &apos;&apos;) = &apos;{1}&apos;
        ///AND ISNULL(KeyFld_3_V, &apos;&apos;) = &apos;{2}&apos;
        ///AND ISNULL(KeyFld_4_V, &apos;&apos;) = &apos;{3}&apos;.
        /// </summary>
        internal static string TaxDetermination_GetDisplayOrder {
            get {
                return ResourceManager.GetString("TaxDetermination_GetDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT
        ///	&apos;Y&apos;	#,
        ///	[dbo].FN_GET_KEYFIELDDESCRIPTION(TCD1.KeyFld_1, TCD2.KeyFld_1_V) {1},
        ///	[dbo].FN_GET_KEYFIELDDESCRIPTION(TCD1.KeyFld_2, TCD2.KeyFld_2_V) {2},
        ///	[dbo].FN_GET_KEYFIELDDESCRIPTION(TCD1.KeyFld_3, TCD2.KeyFld_3_V) {3},
        ///	[dbo].FN_GET_KEYFIELDDESCRIPTION(TCD1.KeyFld_4, TCD2.KeyFld_4_V) {4}
        ///FROM TCD1
        ///	INNER JOIN TCD2
        ///		ON TCD2.Tcd1Id = TCD1.AbsId
        ///WHERE TCD1.TcdId = 1
        ///AND TCD1.Priority = {0}.
        /// </summary>
        internal static string TaxDetermination_GetFields {
            get {
                return ResourceManager.GetString("TaxDetermination_GetFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT 
        ///	DispOrder DisplayOrder, 
        ///	KeyFld_1_V Value1, 
        ///	ISNULL(KeyFld_2_V, &apos;&apos;) Value2,
        ///	ISNULL(KeyFld_3_V, &apos;&apos;) Value3,
        ///	ISNULL(KeyFld_4_V, &apos;&apos;) Value4
        ///FROM TCD2
        ///WHERE Tcd1Id = {0}.
        /// </summary>
        internal static string TaxDetermination_GetKeyValues {
            get {
                return ResourceManager.GetString("TaxDetermination_GetKeyValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT MAX(DispOrder) FROM TCD2 WHERE Tcd1Id = {0}.
        /// </summary>
        internal static string TaxDetermination_GetMaxDisplayOrder {
            get {
                return ResourceManager.GetString("TaxDetermination_GetMaxDisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT TCD3.Tcd2Id, OUSG.Usage, TCD5.TaxCode, TCD5.ExpTaxCode TaxCodeExpense
        ///FROM TCD1
        ///	INNER JOIN TCD2
        ///		ON TCD2.Tcd1Id = TCD1.AbsId
        ///	INNER JOIN TCD3
        ///		ON TCD3.Tcd2Id = TCD2.AbsId
        ///	INNER JOIN TCD5
        ///		ON TCD5.Tcd3Id = TCD3.AbsId
        ///	INNER JOIN OUSG
        ///		ON OUSG.ID = TCD5.UsageCode
        ///WHERE TCD1.TcdId = 1
        ///AND TCD1.Priority = {0}.
        /// </summary>
        internal static string TaxDeterminationUsage_GetToExport {
            get {
                return ResourceManager.GetString("TaxDeterminationUsage_GetToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT
        ///	TCD2.AbsId Tcd2Id,
        ///	dbo.FN_TAXCODE_EXPORT(TCD1.KeyFld_1, TCD2.KeyFld_1_V) Value1,
        ///	dbo.FN_TAXCODE_EXPORT(TCD1.KeyFld_2, TCD2.KeyFld_2_V) Value2,
        ///	dbo.FN_TAXCODE_EXPORT(TCD1.KeyFld_3, TCD2.KeyFld_3_V) Value3,
        ///	dbo.FN_TAXCODE_EXPORT(TCD1.KeyFld_4, TCD2.KeyFld_4_V) Value4,
        ///	TCD3.EfctFrom DateFrom,
        ///	TCD3.EfctTo	DateTo
        ///FROM TCD1
        ///	INNER JOIN TCD2
        ///		ON TCD2.Tcd1Id = TCD1.AbsId
        ///	INNER JOIN TCD3
        ///		ON TCD3.Tcd2Id = TCD2.AbsId
        ///WHERE TCD1.TcdId = 1
        ///AND TCD1.Priority = {0}.
        /// </summary>
        internal static string TaxDeterminationValues_GetToExport {
            get {
                return ResourceManager.GetString("TaxDeterminationValues_GetToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT UFD1.FldValue 
        ///FROM CUFD
        ///    INNER JOIN UFD1 
        ///        ON CUFD.TableID = UFD1.TableID
        ///        AND CUFD.FieldID = UFD1.FieldID
        /// WHERE CUFD.TableID = &apos;{0}&apos;
        /// AND CUFD.AliasID = &apos;{1}&apos;.
        /// </summary>
        internal static string UDF_GetValidValues {
            get {
                return ResourceManager.GetString("UDF_GetValidValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT ID FROM OUSG WHERE LOWER(Usage) = &apos;{0}&apos; OR LOWER(Descr) = &apos;{0}&apos;.
        /// </summary>
        internal static string Usage_GetIdByDescription {
            get {
                return ResourceManager.GetString("Usage_GetIdByDescription", resourceCulture);
            }
        }
    }
}
